// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: api/enum.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OwnerType int32

const (
	OwnerType_NETWORK  OwnerType = 0
	OwnerType_MERCHANT OwnerType = 1
	OwnerType_MEMBER   OwnerType = 2
)

// Enum value maps for OwnerType.
var (
	OwnerType_name = map[int32]string{
		0: "NETWORK",
		1: "MERCHANT",
		2: "MEMBER",
	}
	OwnerType_value = map[string]int32{
		"NETWORK":  0,
		"MERCHANT": 1,
		"MEMBER":   2,
	}
)

func (x OwnerType) Enum() *OwnerType {
	p := new(OwnerType)
	*p = x
	return p
}

func (x OwnerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OwnerType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_enum_proto_enumTypes[0].Descriptor()
}

func (OwnerType) Type() protoreflect.EnumType {
	return &file_api_enum_proto_enumTypes[0]
}

func (x OwnerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OwnerType.Descriptor instead.
func (OwnerType) EnumDescriptor() ([]byte, []int) {
	return file_api_enum_proto_rawDescGZIP(), []int{0}
}

type AccountType int32

const (
	AccountType_TOTAL             AccountType = 0
	AccountType_NETWORK_PROMOTION AccountType = 1
	AccountType_NETWORK_REVOKE    AccountType = 2
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "TOTAL",
		1: "NETWORK_PROMOTION",
		2: "NETWORK_REVOKE",
	}
	AccountType_value = map[string]int32{
		"TOTAL":             0,
		"NETWORK_PROMOTION": 1,
		"NETWORK_REVOKE":    2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_enum_proto_enumTypes[1].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_api_enum_proto_enumTypes[1]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_api_enum_proto_rawDescGZIP(), []int{1}
}

type TransactionType int32

const (
	TransactionType_EARN_POINTS            TransactionType = 0
	TransactionType_REDEEM_POINTS          TransactionType = 1
	TransactionType_REFUND_EARNED_POINTS   TransactionType = 2
	TransactionType_REFUND_REDEEMED_POINTS TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "EARN_POINTS",
		1: "REDEEM_POINTS",
		2: "REFUND_EARNED_POINTS",
		3: "REFUND_REDEEMED_POINTS",
	}
	TransactionType_value = map[string]int32{
		"EARN_POINTS":            0,
		"REDEEM_POINTS":          1,
		"REFUND_EARNED_POINTS":   2,
		"REFUND_REDEEMED_POINTS": 3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_enum_proto_enumTypes[2].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_api_enum_proto_enumTypes[2]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_api_enum_proto_rawDescGZIP(), []int{2}
}

var File_api_enum_proto protoreflect.FileDescriptor

var file_api_enum_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x2a, 0x32, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x4d, 0x45, 0x52, 0x43, 0x48, 0x41, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x43, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x4f, 0x54, 0x41,
	0x4c, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x50,
	0x52, 0x4f, 0x4d, 0x4f, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x45,
	0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x52, 0x45, 0x56, 0x4f, 0x4b, 0x45, 0x10, 0x02, 0x2a, 0x6b,
	0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x41, 0x52, 0x4e, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x53,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x44, 0x45, 0x45, 0x4d, 0x5f, 0x50, 0x4f, 0x49,
	0x4e, 0x54, 0x53, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x46, 0x55, 0x4e, 0x44, 0x5f,
	0x45, 0x41, 0x52, 0x4e, 0x45, 0x44, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x53, 0x10, 0x02, 0x12,
	0x1a, 0x0a, 0x16, 0x52, 0x45, 0x46, 0x55, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x44, 0x45, 0x45, 0x4d,
	0x45, 0x44, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x53, 0x10, 0x03, 0x42, 0x18, 0x5a, 0x16, 0x6c,
	0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_enum_proto_rawDescOnce sync.Once
	file_api_enum_proto_rawDescData = file_api_enum_proto_rawDesc
)

func file_api_enum_proto_rawDescGZIP() []byte {
	file_api_enum_proto_rawDescOnce.Do(func() {
		file_api_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_enum_proto_rawDescData)
	})
	return file_api_enum_proto_rawDescData
}

var file_api_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_enum_proto_goTypes = []any{
	(OwnerType)(0),       // 0: api.OwnerType
	(AccountType)(0),     // 1: api.AccountType
	(TransactionType)(0), // 2: api.TransactionType
}
var file_api_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_enum_proto_init() }
func file_api_enum_proto_init() {
	if File_api_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_enum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_enum_proto_goTypes,
		DependencyIndexes: file_api_enum_proto_depIdxs,
		EnumInfos:         file_api_enum_proto_enumTypes,
	}.Build()
	File_api_enum_proto = out.File
	file_api_enum_proto_rawDesc = nil
	file_api_enum_proto_goTypes = nil
	file_api_enum_proto_depIdxs = nil
}
